In [11]:
import numpy as np
a=np.array((10,20,30,40,50))
print(a,"\n",type(a))
print("\n")
b=np.array([[1,2,3],[4,5,6]])
print(b,"\n",type(b))
print("\n")
c=np.zeros(2)
print(c)
print("\n")
d=np.array([[10,20,30],[7.8,9,10]],dtype=float)
print(d)
print("\n")
e=np.empty((2,2))
print(e)#they are memory locations which are allocated by interpreter




[10 20 30 40 50] 
 <class 'numpy.ndarray'>


[[1 2 3]
 [4 5 6]] 
 <class 'numpy.ndarray'>


[0. 0.]


[[10.  20.  30. ]
 [ 7.8  9.  10. ]]


[[0.00000000e+000 1.00248885e-311]
 [1.00248885e-311 1.00248885e-311]]
