In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:")
print(arr)

parts = np.split(arr, [3, 7])

print("\nPart 1:")
print(parts[0])

print("\nPart 2:")
print(parts[1])

print("\nPart 3:")
print(parts[2])

Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Part 1:
[10 20 30]

Part 2:
[40 50 60 70]

Part 3:
[ 80  90 100]


In [2]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original Array:")
print(arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original Array:")
print(arr)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
result_a = arr[:2, :3]

print("First two rows and three columns:")
print(result_a)

First two rows and three columns:
[[1 2 3]
 [5 6 7]]


In [6]:
result_c = arr[::-1]

print("Rows reversed:")
print(result_c)

Rows reversed:
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [7]:
import numpy as np

arr = np.array([10, 20, 30])

print("Original 1-D array:")
print(arr)

print("Shape:", arr.shape)

Original 1-D array:
[10 20 30]
Shape: (3,)


In [8]:
row_vector = arr[np.newaxis, :]

print("Row vector:")
print(row_vector)

print("Shape:", row_vector.shape)

Row vector:
[[10 20 30]]
Shape: (1, 3)


In [10]:
import numpy as np

one_d = np.array([1, 2, 3])

two_d = np.array([
    [4, 5, 6],
    [7, 8, 9]
])

result = np.vstack((one_d, two_d))

print("1-D array:")
print(one_d)

print("\n2-D array:")
print(two_d)

print("\nAfter vertical stacking:")
print(result)

1-D array:
[1 2 3]

2-D array:
[[4 5 6]
 [7 8 9]]

After vertical stacking:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np

one_d = np.array([1, 2, 3])

two_d = np.array([
    [4, 5, 6],
    [7, 8, 9]
])

result = np.vstack((one_d, two_d))

print("1-D array:")
print(one_d)

print("\n2-D array:")
print(two_d)

print("\nAfter vertical stacking:")
print(result)

1-D array:
[1 2 3]

2-D array:
[[4 5 6]
 [7 8 9]]

After vertical stacking:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:")
print(arr)

parts = np.split(arr, [3, 7])

print("\nPart 1:")
print(parts[0])

print("\nPart 2:")
print(parts[1])

print("\nPart 3:")
print(parts[2])

Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Part 1:
[10 20 30]

Part 2:
[40 50 60 70]

Part 3:
[ 80  90 100]


In [14]:
np.split(arr, [3, 7])

[array([10, 20, 30]), array([40, 50, 60, 70]), array([ 80,  90, 100])]